<a href="https://colab.research.google.com/github/snehaxavier2110/Mtech_coursework/blob/main/mlp_electricity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('/content/lstm_forecast_comparison.csv')

In [ ]:
data

,date,152,lstm_forecast,sarima_forecast,Unnamed: 4,Unnamed: 5
0,01-01-2018 03:00,796,773.686584,820.627100,NaN,NaN
1,01-01-2018 04:00,746,749.334168,718.173882,NaN,NaN
2,01-01-2018 05:00,762,727.288696,690.631164,NaN,NaN
3,01-01-2018 06:00,802,774.834534,748.946800,NaN,NaN
4,01-01-2018 07:00,863,856.281311,847.535625,NaN,NaN
5,01-01-2018 08:00,870,933.284241,904.162003,NaN,NaN
6,01-01-2018 09:00,913,977.201782,915.990411,NaN,NaN
7,01-01-2018 10:00,1064,1120.973633,1065.967452,NaN,NaN
8,01-01-2018 11:00,1379,1257.217041,1124.009391,NaN,NaN
9,01-01-2018 12:00,1635,1389.403564,1452.134065,NaN,NaN
10,01-01-2018 13:00,1668,1531.686035,1769.365860,NaN,NaN
11,01-01-2018 14:00,1638,1608.230225,1719.561040,NaN,NaN
12,01-01-2018 15:00,1411,1627.206177,1653.669017,NaN,NaN
13,01-01-2018 16:00,1438,1548.525513,1448.360381,NaN,NaN
14,01-01-2018 17:00,1483,1495.113525,1427.721050,NaN,NaN
15,01-01-2018 18:00,1610,1477.319458,1475.924510,NaN,NaN
16,01-01-2018 19:00,1899,1538.156128,1556.617453,NaN,NaN
17,01-01-2018 20:00,1926,1720.541260,1850.607554,NaN,NaN
18,01-01-2018 21:00,1870,1761.351685,1889.085022,NaN,NaN
19,01-01-2018 22:00,1727,1772.328369,1843.271519,NaN,NaN
20,01-01-2018 23:00,1632,1654.821899,1653.193972,NaN,NaN
21,02-01-2018 00:00,1373,1402.117432,1537.086863,NaN,NaN
22,02-01-2018 01:00,1135,1100.749023,1235.560206,NaN,NaN
23,02-01-2018 02:00,832,904.102356,1015.916153,NaN,NaN

In [ ]:
X = data[['lstm_forecast', 'sarima_forecast']]
y = data['152']

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

model = Sequential()
model.add(Input(shape=(X.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,305 (9.00 KB)

 Trainable params: 2,305 (9.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = model.fit(X, y, epochs=100, batch_size=32)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1225824.0000 - mae: 1056.0941
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 1139032.2500 - mae: 1017.5311
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1055051.5000 - mae: 978.7891
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 974358.8125 - mae: 940.0759
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 905010.1875 - mae: 905.4763
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 838766.0625 - mae: 871.1291
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 775326.5000 - mae: 836.9495
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 715340.3125 - mae: 803.3245
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 658715.9375 - mae: 770.1636
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 604508.6875 - mae: 737.0283
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 552560.6875 - mae: 703.8105
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 502893.5000 - mae: 670.5157
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 455549.2500 - mae: 637.1650
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 410584.7812 - mae: 603.7917
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 368207.4688 - mae: 570.5493
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 328308.9688 - mae: 537.3810
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 290850.6562 - mae: 504.2660
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 255865.5156 - mae: 471.2477
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 223943.4375 - mae: 438.9788
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 195325.3906 - mae: 407.8829
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 168953.7031 - mae: 376.9726
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 144837.4844 - mae: 346.3104
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 122975.8828 - mae: 315.9669
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 103353.5703 - mae: 286.0182
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 85938.9609 - mae: 256.5455
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 70684.3672 - mae: 227.6368
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 57523.7695 - mae: 199.4222
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 46372.1680 - mae: 175.3430
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 37127.2383 - mae: 153.1496
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 29668.9121 - mae: 131.7472
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 23859.9688 - mae: 111.2552
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 19548.0332 - mae: 96.5672
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 16567.7480 - mae: 88.4480
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 14743.8838 - mae: 84.2305
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 13895.1680 - mae: 83.7193
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 13838.5186 - mae: 86.8193
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 14393.5078 - mae: 92.4648
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 15387.4951 - mae: 98.7389
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 16659.6973 - mae: 104.8030
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 18065.5332 - mae: 110.1971
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 19479.9199 - mae: 115.0041
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 20799.5801 - mae: 119.1566
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 21944.4238 - mae: 122.4517
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 22857.5840 - mae: 125.3173
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 23504.5918 - mae: 127.4173
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 23871.4199 - mae: 128.7130
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 23961.9219 - mae: 129.0292
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 23794.6855 - mae: 128.4443
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 23399.6152 - mae: 127.0426
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 22814.3965 - mae: 125.1813
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 22081.3887 - mae: 122.8310
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 21244.3770 - mae: 120.4677
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 20346.3340 - mae: 117.7793
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 19427.0215 - mae: 114.8291
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 18521.6797 - mae: 111.7555
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 17659.8398 - mae: 108.7517
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 16864.8984 - mae: 105.6678
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 16153.8047 - mae: 102.5503
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 15537.4014 - mae: 99.4991
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 15020.8281 - mae: 96.7553
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 14604.2188 - mae: 94.0851
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 14283.5186 - mae: 91.5158
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 14051.3467 - mae: 89.2731
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13897.8945 - mae: 87.6050
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 13811.7891 - mae: 86.3452
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 13780.7939 - mae: 85.4061
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 13792.6143 - mae: 84.5538
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 13835.4111 - mae: 83.8690
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 13898.2266 - mae: 83.7109
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 13971.3623 - mae: 83.6928
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 14046.6045 - mae: 83.6775
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 14117.3174 - mae: 83.6680
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 14178.5068 - mae: 83.7369
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 14226.6924 - mae: 83.7875
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 14259.8701 - mae: 83.8207
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 14277.3154 - mae: 83.8377
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 14279.3857 - mae: 83.8396
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 14267.3057 - mae: 83.8278
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 14242.9463 - mae: 83.8036
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 14208.6279 - mae: 83.7685
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 14166.8857 - mae: 83.7238
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 14120.3369 - mae: 83.6710
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 14071.4688 - mae: 83.6716
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 14022.5811 - mae: 83.6806
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13975.6523 - mae: 83.6902
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13932.2969 - mae: 83.7001
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 13893.6768 - mae: 83.7102
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 13860.6143 - mae: 83.7203
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 13833.4912 - mae: 83.8785
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13812.3721 - mae: 84.1283
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 13797.0068 - mae: 84.4316
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13786.8857 - mae: 84.7191
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13781.3174 - mae: 84.9877
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 13779.5391 - mae: 85.2351
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 13780.6875 - mae: 85.4592
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 13783.9092 - mae: 85.6588
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13788.4189 - mae: 85.8329
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 13793.4951 - mae: 85.9811
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 13798.5352 - mae: 86.1032
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 13803.0742 - mae: 86.1999

In [ ]:
from sklearn.metrics import mean_absolute_error

mlp_predictions = model.predict(X)

lstm_mae = mean_absolute_error(y, data['lstm_forecast'])
sarima_mae = mean_absolute_error(y, data['sarima_forecast'])
mlp_mae = mean_absolute_error(y, mlp_predictions)

print(f'MAE for LSTM forecast: {lstm_mae:.2f}')
print(f'MAE for SARIMA forecast: {sarima_mae:.2f}')
print(f'MAE for MLP predictions: {mlp_mae:.2f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
MAE for LSTM forecast: 90.09
MAE for SARIMA forecast: 96.56
MAE for MLP predictions: 86.27

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

# Define the Early Stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)


# Re-compile and train the model with the Early Stopping callback
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = model.fit(X_train, y_train, epochs=100, batch_size=32, callbacks=[early_stopping], validation_data=(X_val, y_val)) # Add validation_data=(X_val, y_val) if you have a validation set

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 10669.8877 - mae: 79.8069 - val_loss: 35450.9570 - val_mae: 128.7631
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step - loss: 9788.0078 - mae: 72.8917 - val_loss: 40693.0547 - val_mae: 146.9712
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 10415.1289 - mae: 73.6057 - val_loss: 38733.9141 - val_mae: 140.4358
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 10122.5557 - mae: 72.7868 - val_loss: 34342.3320 - val_mae: 126.2003
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 9724.4189 - mae: 73.2549 - val_loss: 30393.7910 - val_mae: 117.8763
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 9778.0596 - mae: 74.6668 - val_loss: 28384.5664 - val_mae: 115.0701
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 10020.9131 - mae: 75.5669 - val_loss: 28426.0508 - val_mae: 115.1368
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 10014.2393 - mae: 75.5263 - val_loss: 29990.0664 - val_mae: 117.3507
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 9812.7773 - mae: 74.8243 - val_loss: 32461.2129 - val_mae: 122.2579
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 9688.9629 - mae: 73.9024 - val_loss: 34982.1758 - val_mae: 127.4934
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 9752.6953 - mae: 73.0432 - val_loss: 36549.5781 - val_mae: 132.6714
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 9869.2686 - mae: 72.5420 - val_loss: 36609.5781 - val_mae: 132.8733
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 9873.8896 - mae: 72.5230 - val_loss: 35357.1953 - val_mae: 128.2555
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 9773.5195 - mae: 72.9208 - val_loss: 33445.8477 - val_mae: 124.3581
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 9691.0957 - mae: 73.5581 - val_loss: 31612.5820 - val_mae: 120.3893
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 9705.9395 - mae: 74.2096 - val_loss: 30422.8711 - val_mae: 117.9920

In [ ]:
from sklearn.metrics import mean_absolute_error

mlp_predictions = model.predict(X)

lstm_mae = mean_absolute_error(y, data['lstm_forecast'])
sarima_mae = mean_absolute_error(y, data['sarima_forecast'])
mlp_mae = mean_absolute_error(y, mlp_predictions)

print(f'MAE for LSTM forecast: {lstm_mae:.2f}')
print(f'MAE for SARIMA forecast: {sarima_mae:.2f}')
print(f'MAE for MLP predictions: {mlp_mae:.2f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
MAE for LSTM forecast: 90.09
MAE for SARIMA forecast: 96.56
MAE for MLP predictions: 83.80

In [ ]:
data['mlp_predictions'] = mlp_predictions
data

,date,152,lstm_forecast,sarima_forecast,Unnamed: 4,Unnamed: 5,mlp_predictions
0,01-01-2018 03:00,796,773.686584,820.627100,NaN,NaN,802.029297
1,01-01-2018 04:00,746,749.334168,718.173882,NaN,NaN,744.872498
2,01-01-2018 05:00,762,727.288696,690.631164,NaN,NaN,720.292175
3,01-01-2018 06:00,802,774.834534,748.946800,NaN,NaN,772.852722
4,01-01-2018 07:00,863,856.281311,847.535625,NaN,NaN,862.345337
5,01-01-2018 08:00,870,933.284241,904.162003,NaN,NaN,931.716003
6,01-01-2018 09:00,913,977.201782,915.990411,NaN,NaN,962.754578
7,01-01-2018 10:00,1064,1120.973633,1065.967452,NaN,NaN,1110.709229
8,01-01-2018 11:00,1379,1257.217041,1124.009391,NaN,NaN,1215.891235
9,01-01-2018 12:00,1635,1389.403564,1452.134065,NaN,NaN,1431.166626
10,01-01-2018 13:00,1668,1531.686035,1769.365860,NaN,NaN,1647.907349
11,01-01-2018 14:00,1638,1608.230225,1719.561040,NaN,NaN,1672.670288
12,01-01-2018 15:00,1411,1627.206177,1653.669017,NaN,NaN,1656.504517
13,01-01-2018 16:00,1438,1548.525513,1448.360381,NaN,NaN,1524.201538
14,01-01-2018 17:00,1483,1495.113525,1427.721050,NaN,NaN,1483.847656
15,01-01-2018 18:00,1610,1477.319458,1475.924510,NaN,NaN,1493.347656
16,01-01-2018 19:00,1899,1538.156128,1556.617453,NaN,NaN,1563.131958
17,01-01-2018 20:00,1926,1720.541260,1850.607554,NaN,NaN,1794.034058
18,01-01-2018 21:00,1870,1761.351685,1889.085022,NaN,NaN,1834.326050
19,01-01-2018 22:00,1727,1772.328369,1843.271519,NaN,NaN,1821.768433
20,01-01-2018 23:00,1632,1654.821899,1653.193972,NaN,NaN,1672.725708
21,02-01-2018 00:00,1373,1402.117432,1537.086863,NaN,NaN,1474.113647
22,02-01-2018 01:00,1135,1100.749023,1235.560206,NaN,NaN,1169.329956
23,02-01-2018 02:00,832,904.102356,1015.916153,NaN,NaN,960.917969